version: 2
jobs:
  build:
    docker:
      # TODO: Convert to image with dep preinstalled
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - go get -v -u github.com/golang/dep/cmd/dep
      - checkout
      - run: dep ensure
      - run: go test -v ./...
